# NOTE: Generated By HttpRunner v3.1.4
# FROM: create.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseCreate(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/login/submit")
            .post("https://mubu.com/api/login/submit")
            .with_headers(
                **{
                    "Accept": "application/json, text/javascript, */*; q=0.01",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "55",
                    "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
                    "Cookie": "data_unique_id=e194d05a-fafd-45c2-9c00-244bf6d07baf; language=en-US; country=US; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1616326049; _ga=GA1.2.1032845546.1616326049; _gid=GA1.2.1424744806.1616326049; reg_from=https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D4FSUuObRaNpbrJBQJVSrUxIg6HoxHdipLZz09_GgEnG%26wd%3D%26eqid%3De48b29e400036eee0000000560572d9b; reg_entrance=https%3A%2F%2Fmubu.com%2F; csrf_token=0061f05c-6441-42d2-954a-efc3d2230c09; SESSION=724e5b6a-575d-411d-b803-03f16f48d15b; _gat=1; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1616332485; _gat_UA-77727571-3=1; reg_prepareId=17854ed0968-17854ed0965-4f22-a9db-27789b381cd5; reg_focusId=c3e40de8-f4ae-4f22-a9db-17854ed0dbd; SLARDAR_WEB_ID=eeb6bea1-9e54-4df8-b1c2-e7a576bf3824",
                    "Host": "mubu.com",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/login/password",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-origin",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "X-Requested-With": "XMLHttpRequest",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616332485",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616326049",
                    "SESSION": "724e5b6a-575d-411d-b803-03f16f48d15b",
                    "SLARDAR_WEB_ID": "eeb6bea1-9e54-4df8-b1c2-e7a576bf3824",
                    "_ga": "GA1.2.1032845546.1616326049",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1424744806.1616326049",
                    "country": "US",
                    "csrf_token": "0061f05c-6441-42d2-954a-efc3d2230c09",
                    "data_unique_id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "c3e40de8-f4ae-4f22-a9db-17854ed0dbd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D4FSUuObRaNpbrJBQJVSrUxIg6HoxHdipLZz09_GgEnG%26wd%3D%26eqid%3De48b29e400036eee0000000560572d9b",
                    "reg_prepareId": "17854ed0968-17854ed0965-4f22-a9db-27789b381cd5",
                }
            )
            .with_data(
                {
                    "password": "15850748167dzy",
                    "phone": "15850748167",
                    "remember": "true",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", None)
        ),
        Step(
            RunRequest("/app")
            .get("https://mubu.com/app")
            .with_headers(
                **{
                    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Cookie": "data_unique_id=e194d05a-fafd-45c2-9c00-244bf6d07baf; language=en-US; country=US; Hm_lvt_4426cbb0486a79ea049b4ad52d81b504=1616326049; _ga=GA1.2.1032845546.1616326049; _gid=GA1.2.1424744806.1616326049; reg_from=https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D4FSUuObRaNpbrJBQJVSrUxIg6HoxHdipLZz09_GgEnG%26wd%3D%26eqid%3De48b29e400036eee0000000560572d9b; reg_entrance=https%3A%2F%2Fmubu.com%2F; csrf_token=0061f05c-6441-42d2-954a-efc3d2230c09; SESSION=724e5b6a-575d-411d-b803-03f16f48d15b; _gat=1; Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504=1616332485; _gat_UA-77727571-3=1; reg_prepareId=17854ed0968-17854ed0965-4f22-a9db-27789b381cd5; reg_focusId=c3e40de8-f4ae-4f22-a9db-17854ed0dbd; SLARDAR_WEB_ID=eeb6bea1-9e54-4df8-b1c2-e7a576bf3824; Jwt-Token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA; user_persistence=f3a9ee80-a3df-444b-8019-cfefec6babe2",
                    "Host": "mubu.com",
                    "Referer": "https://mubu.com/login/password",
                    "Sec-Fetch-Dest": "document",
                    "Sec-Fetch-Mode": "navigate",
                    "Sec-Fetch-Site": "same-origin",
                    "Sec-Fetch-User": "?1",
                    "Upgrade-Insecure-Requests": "1",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1616332485",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1616326049",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "SESSION": "724e5b6a-575d-411d-b803-03f16f48d15b",
                    "SLARDAR_WEB_ID": "eeb6bea1-9e54-4df8-b1c2-e7a576bf3824",
                    "_ga": "GA1.2.1032845546.1616326049",
                    "_gat": "1",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1424744806.1616326049",
                    "country": "US",
                    "csrf_token": "0061f05c-6441-42d2-954a-efc3d2230c09",
                    "data_unique_id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "c3e40de8-f4ae-4f22-a9db-17854ed0dbd",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D4FSUuObRaNpbrJBQJVSrUxIg6HoxHdipLZz09_GgEnG%26wd%3D%26eqid%3De48b29e400036eee0000000560572d9b",
                    "reg_prepareId": "17854ed0968-17854ed0965-4f22-a9db-27789b381cd5",
                    "user_persistence": "f3a9ee80-a3df-444b-8019-cfefec6babe2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "text/html; charset=utf-8")
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "761c0472-8bc8-412e-9cab-dcae7deb5fde",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "12",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "1f87ad06-b62b-449b-88d0-16bac6f1c637",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "72ab106a-be55-47a2-aa4e-5310c8a70d2a",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "0",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "3d85edca-0120-406a-9d7c-56ca2115beef",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "10",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "80586cb9-dbdd-4cd9-8d65-8adc8a76e427",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "30",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "211439e5-6515-43bb-9153-cb06b1533c86",
                }
            )
            .with_json({"folderId": 0, "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "10",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "f31e2202-43ad-4072-8bb3-274e27ef22cd",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "42",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "55500884-b3ea-46c4-baa1-bc2a5ee358b3",
                }
            )
            .with_json({"folderId": "2lH-0vPgUBJ", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/create_folder")
            .post("https://api2.mubu.com/v3/api/list/create_folder")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "48",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "a4f2e281-7fb3-4c4c-9bab-168c7bda9fb5",
                }
            )
            .with_json({"folderId": "2lH-0vPgUBJ", "name": "安安生生"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "Accept": "application/json, text/plain, */*",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Accept-Language": "zh-CN,zh;q=0.9",
                    "Connection": "keep-alive",
                    "Content-Length": "42",
                    "Content-Type": "application/json;charset=UTF-8",
                    "Host": "api2.mubu.com",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg5MjQ1MzQsImlhdCI6MTYxNjMzMjUzNH0.vMtgwtvhoN4G5ddXTcI4Hl2hQs1GRD73i8X8QAi5UiUx7NAJbH7Gbxdimf3gUI-0sWhqgXP9gcQvI7h-EONLZA",
                    "Origin": "https://mubu.com",
                    "Referer": "https://mubu.com/",
                    "Sec-Fetch-Dest": "empty",
                    "Sec-Fetch-Mode": "cors",
                    "Sec-Fetch-Site": "same-site",
                    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36",
                    "data-unique-id": "e194d05a-fafd-45c2-9c00-244bf6d07baf",
                    "sec-ch-ua": '"Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"',
                    "sec-ch-ua-mobile": "?0",
                    "version": "3.0.0.21201",
                    "x-request-id": "55500884-b3ea-46c4-baa1-bc2a5ee358b3",
                }
            )
            .with_json({"folderId": "1_rQhNLS1JJ", "source": "home"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json;charset=UTF-8")
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseCreate().test_start()
