# NOTE: Generated By HttpRunner v3.1.4
# FROM: mubu.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseMubu(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/app/folders/recent")
            .get("https://mubu.com/app/folders/recent")
            .with_headers(
                **{
                    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "cache-control": "max-age=0",
                    "referer": "https://mubu.com/app",
                    "sec-fetch-dest": "document",
                    "sec-fetch-mode": "navigate",
                    "sec-fetch-site": "same-origin",
                    "sec-fetch-user": "?1",
                    "upgrade-insecure-requests": "1",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                }
            )
            .with_cookies(
                **{
                    "Hm_lpvt_4426cbb0486a79ea049b4ad52d81b504": "1615895536",
                    "Hm_lvt_4426cbb0486a79ea049b4ad52d81b504": "1615895535",
                    "Jwt-Token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "SESSION": "7270b46c-a866-462b-8901-eae928134757",
                    "SLARDAR_WEB_ID": "828c440e-0e14-47ca-8892-80ac55773af3",
                    "_ga": "GA1.2.1089513375.1615895534",
                    "_gat_UA-77727571-3": "1",
                    "_gid": "GA1.2.1196892541.1615895534",
                    "country": "US",
                    "csrf_token": "2ac274a9-430c-4ba0-a49e-5401c40e9e8d",
                    "data_unique_id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "language": "en-US",
                    "reg_entrance": "https%3A%2F%2Fmubu.com%2F",
                    "reg_focusId": "3e095b8d-377b-4873-8581-1783ae12696",
                    "reg_from": "https%3A%2F%2Fwww.baidu.com%2Flink%3Furl%3D-RXmEDPPQlki1jrmKURj4OXCgSPCNfEkUTNrdeF1gku%26wd%3D%26eqid%3Da2263e9a0004560d0000000560509beb",
                    "reg_prepareId": "1783ae122da-1783ae122d6-4873-8581-a5ab61232657",
                    "user_persistence": "f3a9ee80-a3df-444b-8019-cfefec6babe2",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("/v3/api/user/profile")
            .post("https://api2.mubu.com/v3/api/user/profile")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "0",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "8c53b647-61f5-4dc5-b03e-6c1bfbcc6bf3",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get")
            .post("https://api2.mubu.com/v3/api/list/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "60",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "97cbc0a6-0527-4792-a45a-3eebc1810b97",
                }
            )
            .with_json(
                {"folderId": 0, "keywords": "", "sort": "time", "source": "recent"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/item_count")
            .post("https://api2.mubu.com/v3/api/list/item_count")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "32",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "66fd3aea-4937-407e-bda0-ab3723e68484",
                }
            )
            .with_json({"folderId": 0, "source": "recent"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/get_all_documents_page")
            .post("https://api2.mubu.com/v3/api/list/get_all_documents_page")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "12",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "11114083-881a-4f5a-8087-cb2d9edfc7e7",
                }
            )
            .with_json({"start": ""})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/list/star_relation/get")
            .get("https://api2.mubu.com/v3/api/list/star_relation/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "9d2fc75d-3b1e-4716-bd9e-8baae0fc4ea1",
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/user/get_user_params")
            .post("https://api2.mubu.com/v3/api/user/get_user_params")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "0",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "1da723bd-093a-4547-859f-8798314bdb13",
                }
            )
            .with_data("")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/message/get_message_unread")
            .post("https://api2.mubu.com/v3/api/message/get_message_unread")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "10",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "fd37d2cc-80d1-4bda-a9f0-8dbbea238488",
                }
            )
            .with_json({"page": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
        Step(
            RunRequest("/v3/api/advertisement/get")
            .post("https://api2.mubu.com/v3/api/advertisement/get")
            .with_headers(
                **{
                    "accept": "application/json, text/plain, */*",
                    "accept-encoding": "gzip, deflate, br",
                    "accept-language": "zh-CN,zh;q=0.9",
                    "content-length": "10",
                    "content-type": "application/json;charset=UTF-8",
                    "data-unique-id": "e23852bf-c225-43e6-8ce5-ea88ee9496ff",
                    "jwt-token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJhcHAiOiJtdWJ1Iiwic3ViIjoiMTEzODI5MjUiLCJleHAiOjE2MTg0ODc1NTMsImlhdCI6MTYxNTg5NTU1M30.qQPgP5DQcpnHa5fFFZD-T-iOJ4vDExO_MwIbDxGh6PK3jCDYmCPN0Pi8ZzU82ao8rXqH_ZU69J8zW0W464cgtg",
                    "origin": "https://mubu.com",
                    "referer": "https://mubu.com/",
                    "sec-fetch-dest": "empty",
                    "sec-fetch-mode": "cors",
                    "sec-fetch-site": "same-site",
                    "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36",
                    "version": "3.0.0.21145",
                    "x-request-id": "accda8d7-7c31-4eb5-a618-4e356ef0ec53",
                }
            )
            .with_json({"type": 1})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseMubu().test_start()
